# Foundations with torch

torch made by facebook, it serves to work as a framework to do machine learning tasks, it helps us to lift the all heavy lifting with numbers and there transformations. With awesome gpu support it can fast up calculations with parallel processing power.

With torch we can learn how to use that tool, to design the mathematical models on top of the state of the art library tools which it provides us starting with tensor an generic mathematical object defined for doing mathematical operations into for doing calculation at good scale.

In [5]:
# Tensor basics with torch
import torch
'''
We can reffer the official documentation, but when we get stuck or need a help doing something with numbers
Reading docs is the most awesome way to use the tool, trust me, its better then asking gpt, its dopamine high
'''

# Declare tensor with python standard data structure
tensor = torch.tensor([1,2,3])

tensor # simlpe torch.tensor object declared | Powerfull to do a lot of stuff under the hood | refer the docs for detailed journey

tensor([1, 2, 3])

In [12]:
# Foundational Data basics with tensor behaviour

# Referencing variable behaviour
new_tensor = tensor + 10

print(f"Reffered variable {new_tensor}")

# editing original source
tensor[1] = 49

print(tensor)
print(new_tensor) # This should be not modified is it ?
''' Upon close inspection the reffered
variable with adding 10 have also changed thus we need to be cautious with defining variable flow '''

# Referencing variables and copy pathways
'''With just clone gradients can flow back in reference web, detatch is required | Find out why ?'''
z_tensor = tensor.clone().detach()  # Clean Deep copy
print(z_tensor)

# editing source
tensor[1] = 103
print("The source tensor with edits ", tensor)
print("The reference with deep copy for other state", z_tensor)

# With same we can convert tensor to numpy and bought back them find out how to get pythonic elements through tensor ?

Reffered variable tensor([ 11, 113,  13])
tensor([ 1, 49,  3])
tensor([ 11, 113,  13])
tensor([ 1, 49,  3])
The source tensor with edits  tensor([  1, 103,   3])
The reference with deep copy for other state tensor([ 1, 49,  3])


In [19]:
# Foundational mathematical functions

x = torch.rand(size=(2,2)) # random matrix with 2 X 2 dimension

determinant = torch.det(x.float())
determinant = determinant.item()
reshaped_tensor = x.reshape(1,4) # Its a view of original
'''Explore the other foundations with Linear algebra operations we can do with tensors'''
# Making edits with the source
x[1,1] = 3 # changed at position 1,1

print(x)
print(reshaped_tensor)

tensor([[0.1890, 0.1679],
        [0.0128, 3.0000]])
tensor([[0.1890, 0.1679, 0.0128, 3.0000]])


In [29]:
# Making reproducible code with torch
random_seed = 9
torch.manual_seed(random_seed)  # Minecraft world generates with seed :)

random_tensor = torch.rand(size=(10,10))

print(random_tensor) # with no matter how many times you run output would be same

tensor([[0.6558, 0.3020, 0.4799, 0.7774, 0.9180, 0.9310, 0.2604, 0.9534, 0.3804,
         0.4104],
        [0.9510, 0.5686, 0.1381, 0.2069, 0.5139, 0.4850, 0.5193, 0.3468, 0.4477,
         0.6316],
        [0.6947, 0.8215, 0.9111, 0.7315, 0.4468, 0.0725, 0.9196, 0.7834, 0.9715,
         0.5964],
        [0.6265, 0.6688, 0.8898, 0.8178, 0.7261, 0.4066, 0.2465, 0.5823, 0.8214,
         0.4866],
        [0.9382, 0.1651, 0.7763, 0.6066, 0.1668, 0.7295, 0.2111, 0.8447, 0.7742,
         0.0536],
        [0.7574, 0.5797, 0.7400, 0.7412, 0.4269, 0.3049, 0.3977, 0.3234, 0.0525,
         0.6908],
        [0.2824, 0.6235, 0.3730, 0.8572, 0.5366, 0.0363, 0.4987, 0.4254, 0.2376,
         0.9284],
        [0.5906, 0.3453, 0.0070, 0.9552, 0.1192, 0.5466, 0.8069, 0.0749, 0.6649,
         0.9779],
        [0.2977, 0.3315, 0.0481, 0.0036, 0.3613, 0.8805, 0.5022, 0.1243, 0.8245,
         0.5522],
        [0.9638, 0.0129, 0.0446, 0.5520, 0.1035, 0.0709, 0.8512, 0.0886, 0.1004,
         0.6450]])


In [31]:
# Using GPU for computing into hardware
!nvidia-smi # my teacher have A-100 and flexing 40gb ram at gpu :)
torch.cuda.is_available()

Wed Oct  7 14:28:16 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.91.07              Driver Version: 595.91.07      CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8              7W /   60W |      15MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

True

In [36]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3050 6GB Laptop GPU'

In [47]:
# switching to gpu/cpu
device = "cuda"
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device) # Where its present ?

tensor = tensor.to(device)
print(tensor, tensor.device)
print(type(tensor))  # Torch tensor for the gpu acceleration

# Geting GPU Elements into numpy
element = tensor.cpu().numpy()
print(element, type(element))

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
<class 'torch.Tensor'>
[1 2 3] <class 'numpy.ndarray'>
